# Generated by Django 6.0.5 on 2026-05-27 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('student', 'Mahasiswa'), ('freshgraduate', 'Fresh Graduate'), ('lecturer', 'Dosen'), ('freelancer', 'Freelancer'), ('professional', 'Professional')], max_length=30)),
                ('institution', models.CharField(max_length=255)),
                ('study_program', models.CharField(blank=True, max_length=255, null=True)),
                ('occupation', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_field', models.CharField(max_length=255)),
                ('ojs_skill', models.CharField(choices=[('basic', 'Basic'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=30)),
                ('bio', models.TextField(blank=True, null=True)),
                ('cv', models.FileField(upload_to='cv/')),
                ('portfolio', models.FileField(blank=True, null=True, upload_to='portfolio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
