# Generated by Django 6.0.5 on 2026-05-27 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0005_application_assigned_journal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidateprofile',
            name='first_name',
            field=models.CharField(default='Temporary', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='candidateprofile',
            name='last_name',
            field=models.CharField(default='Temporary', max_length=100),
            preserve_default=False,
        ),
    ]
