# Generated by Django 6.0.5 on 2026-05-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0006_candidateprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
