# Generated by Django 6.0.5 on 2026-05-28 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0007_application_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='requirements',
            field=models.TextField(blank=True, null=True),
        ),
    ]
