# Generated by Django 6.0.5 on 2026-05-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0008_position_requirements'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['-created_at'], 'verbose_name': 'Position', 'verbose_name_plural': 'Positions'},
        ),
        migrations.AlterField(
            model_name='position',
            name='fee_scheme',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position_type',
            field=models.CharField(choices=[('project', 'By Project'), ('sharing', 'Revenue Sharing')], default='project', max_length=30),
        ),
        migrations.AlterField(
            model_name='position',
            name='slug',
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
