# Generated by Django 6.0.5 on 2026-05-28 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0009_alter_position_options_alter_position_fee_scheme_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='shortlist_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
