# Generated by Django 6.0.5 on 2026-05-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0010_application_shortlist_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='assigned_interviewer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='onboarding_notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
