# Generated by Django 6.0.5 on 2026-05-29 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recruitment', '0014_application_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='recruitment_open',
            field=models.BooleanField(default=True),
        ),
    ]
